addon-name: "SpartanUI Animated"
addon-description: "animated textures for SpartanUI"
urls:
  curseforge: "https://www.curseforge.com/wow/addons/spartanui-animated"
  wago: "https://addons.wago.io/addons/b6XVZwGp"
  discord: "https://discord.gg/Qc9TRBv"
